#!/bin/bash
killall conky
conky -c ~/.conky/ConkyBar/configs/conky_bg2 &
conky -c ~/.conky/ConkyBar/configs/conky_clock &
conky -c ~/.conky/ConkyBar/configs/conky_txt &
conky -p 3 -c ~/.conky/ConkyBar/configs/conky_network &
conky -p 6 -c ~/.conky/ConkyBar/configs/conky_system &
conky -p 7 -c ~/.conky/ConkyBar/configs/conky_cpu2 &
conky -p 8 -c ~/.conky/ConkyBar/configs/conky_ram &
conky -p 9 -c ~/.conky/ConkyBar/configs/conky_files2 &
conky -p 10 -c ~/.conky/ConkyBar/configs/conky_mpd & 
exit
