#!/usr/bin/env bash

DOM="2014-01-30"
DAYSBETWEEN=$(( ($(date -d $(date +%Y-%m-%d) +%s) - $(date -d $DOM +%s)) / 86400 ))

YEARSCALC=$(( $DAYSBETWEEN / 365 ))
#MONTHSCALC=$(( ($DAYSBETWEEN - ($YEARSCALC * 365)) / 30 ))
#DAYSCALC=$(( $DAYSBETWEEN - ($MONTHSCALC * 30) ))

[[ $YEARSCALC > 0  ]] && YEARS=$YEARSCALC"Y"
#[[ $MONTHSCALC > 0 ]] && MONTHS=$MONTHSCALC"m "
#[[ $DAYSCALC > 0   ]] && DAYS=$DAYSCALC"d"

#WRD=$(sudo /usr/bin/smartctl -a /dev/sda | awk '/Wear_Range_Delta/ {print $10}')
SLL=$(sudo /usr/bin/smartctl -a /dev/sda | awk '/SSD_Life_Left/ {print 100-$5}')
LFW=$(sudo /usr/bin/smartctl -a /dev/sda | awk '/Lifetime_Writes_GiB/ {printf "%3.2f\n",$10/1024}')

echo $SLL"% "$LFW"Tb "$YEARS$MONTHS$DAYS

